[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "CLI for Exocore (Distributed applications framework)"
edition = "2021"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exo"
repository = "https://github.com/appaquet/exocore"
version = "0.1.27"

[dependencies]
anyhow = { version="1.0.98", features = ["backtrace"] }
bytes = "1.10.1"
clap = { version = "4.5.37", features = ["derive", "env"] }
console = "0.15.11"
dialoguer = "0.11.0"
dirs-next = "2.0.0"
exocore-apps-host = {version = "0.1.27", path = "../apps/host"}
exocore-chain = {version = "0.1.27", path = "../chain"}
exocore-core = {version = "0.1.27", path = "../core", features = ["runtime", "logger"]}
exocore-discovery = {version = "0.1.27", path = "../discovery", features = ["server"]}
exocore-protos = {version = "0.1.27", path = "../protos"}
exocore-store = {version = "0.1.27", path = "../store"}
exocore-transport = {version = "0.1.27", path = "../transport", features = ["http-server"]}
futures = "0.3.31"
indicatif = "0.17.11"
log = "0.4.27"
log4rs = "1.3.0"
rand = "0.8"
reqwest = { version = "0.12.15", default-features = false, features = ["rustls-tls"] }
serde = "1.0.219"
serde_derive = "1.0.217"
serde_json = "1.0.140"
tempfile = "3.19.1"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["macros"], default-features = false }
url = "2.5.4"
zip = { version = "2.6.1", features = ["deflate"], default-features = false }
