[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["command-line-interface", "email", "text-editors"]
description = "Exomind, a personal knowledge management tool"
edition = "2021"
keywords = ["knowledge-management", "mobile", "decentralized", "webapp"]
license = "Apache-2.0"
name = "exomind-app"
repository = "https://github.com/appaquet/exomind"
version = "0.1.27"

[lib]
crate-type = ['cdylib']

[dependencies]
anyhow = "1.0.89"
exocore = { version = "0.1.27", path = "../../exocore", default-features = false, features = [
    "apps-sdk",
] }
exomind-protos = { version = "0.1.27", path = "../protos" }
futures = "0.3.30"
log = "0.4.22"
