FROM debian:buster-slim

ARG TARGETPLATFORM
ARG TARGETARCH

RUN echo "Building for platform $TARGETPLATFORM arch $TARGETARCH"
COPY "exo-$TARGETARCH" /usr/local/bin/exo

WORKDIR /volume
ENTRYPOINT ["/usr/local/bin/exo"]
