name: Exomind

public_key: pe5PPd5U5t44CrECvDzbwBNeeeWWXwQkbGNoBoAMb3LjoJ
#TODO: to remove: aekRs33KHr7rdcMfK1m8i9GobnVN1BFvJcpWNgFHFHv5mByE3fiuD2vbpj3NYTKo59TFuXwGGUsxSFrp7gWw4dCVA

schemas:
  - source:
      File: exomind.fd
