# See: https://docs.codecov.io/docs/codecov-yaml

comment: false

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%

    patch:
      default:
        enabled: no

ignore:
  - "**/main.rs"
  - "**/bins/*.rs"
