[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "Distributed applications framework"
edition = "2021"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exocore-apps-example"
repository = "https://github.com/appaquet/exocore"
version = "0.1.27"

[lib]
crate-type = ['cdylib']

[dependencies]
exocore = {version = "0.1.27", path = "../..", default-features = false, features = ["apps-sdk"]}
futures = "0.3.30"
log = "0.4.22"
