[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "Store / indexation layer of Exocore (Distributed applications framework)"
edition = "2021"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exocore-store"
repository = "https://github.com/appaquet/exocore"
version = "0.1.27"

[features]
default = ["local", "remote"]
local = [
  "exocore-chain/engine",
  "exocore-core",
  "exocore-chain",
  "byteorder",
  "crc",
  "extsort",
  "lru",
  "serde",
  "serde_derive",
  "serde_json",
  "tantivy",
]
remote = ["exocore-core", "exocore-transport"]
tests-utils = []

[dependencies]
anyhow = "1.0.95"
async-trait = "0.1.83"
bytes = "1.9.0"
chrono = {version = "0.4.39", features = ["serde"]}
exocore-protos = {version = "0.1.27", path = "../protos"}
futures = "0.3.31"
itertools = "0.13.0"
log = "0.4.22"
smallvec = "1.13.2"
thiserror = "2.0.9"

# local or remote
exocore-chain = {version = "0.1.27", path = "../chain", default-features = false, optional = true}
exocore-core = {version = "0.1.27", path = "../core", optional = true}
exocore-transport = {version = "0.1.27", path = "../transport", default-features = false, optional = true}

# local 
byteorder = {version = "1.5.0", optional = true}
crc = {version = "3.2.1", optional = true}
extsort = {version = "0.4.2", optional = true}
lru = {version = "0.12.5", optional = true}
serde = {version = "1.0.217", optional = true}
serde_derive = {version = "1.0.209", optional = true}
serde_json = {version = "1.0.134", optional = true}
tantivy = {version = "0.19.2", optional = true}

[dev-dependencies]
exocore-chain = {version = "0.1.27", path = "../chain", features = ["tests-utils"]}
exocore-core = {version = "0.1.27", path = "../core", features = ["tests-utils"]}
tempfile = "3.13.0"
tokio = {version = "1.42.0", features = ["macros"], default-features = false}
