[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "Distributed applications framework"
edition = "2021"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exocore-discovery"
repository = "https://github.com/appaquet/exocore"
version = "0.1.27"

[features]
default = ["server"]
server = ["hyper", "tokio"]

[dependencies]
anyhow = "1.0.96"
base64 = "0.22.1"
chrono = { version = "0.4.40", features = ["serde"] }
futures = "0.3.31"
log = "0.4.26"
rand = "0.8"
reqwest = { version = "0.12.12", default-features = false, features = ["json", "rustls-tls"] }
serde = "1.0.218"
serde_derive = "1.0.217"
serde_json = "1.0.139"
thiserror = "2.0.11"
wasm-timer = "0.2.5"

# For server
hyper = { version = "0.14.32", features = ["full"], optional = true }
tokio = { version = "1.43.0", default-features = false, features = ["macros", "time"], optional = true }

[[test]]
name = "discovery"
required-features = ["server"]
