[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "Transport layer of Exocore (Distributed applications framework)"
edition = "2021"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exocore-transport"
repository = "https://github.com/appaquet/exocore"
version = "0.1.27"

[features]
default = ["p2p-full", "http-server"]
http-server = ["hyper", "url", "exocore-core/runtime"]
p2p-base = ["libp2p", "libp2p-mplex"]
p2p-full = ["p2p-base", "libp2p/tcp"]
p2p-web = ["p2p-base", "libp2p/websocket-websys", "libp2p/wasm-bindgen"]
tests-utils = ["exocore-core/tests-utils"]

[dependencies]
anyhow = "1.0.94"
byteorder = "1.5.0"
bytes = "1.9.0"
exocore-core = {version = "0.1.27", path = "../core"}
exocore-protos = {version = "0.1.27", path = "../protos"}
futures = "0.3.31"
hyper = {version = "0.14.30", features = ["full"], optional = true}
libp2p = {version = "0.53.2", optional = true, default-features = false, features = ["noise", "websocket", "yamux", "ping", "identify", "macros", "tokio", "dns"]}
libp2p-identity = { version = "0.2.9", features = ["secp256k1", "ed25519"], default-features = false }
libp2p-mplex = {version = "0.41.0", optional = true}
log = "0.4.22"
pin-project = "1.1.6"
thiserror = "2.0.8"
url = {version = "2.5.2", optional = true}

[dev-dependencies]
exocore-core = {version = "0.1.27", path = "../core", features = ["tests-utils"]}
tokio = {version = "1.42.0", features = ["macros"], default-features = false}
