[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["command-line-interface", "email", "text-editors"]
description = "Exomind, a personal knowledge management tool"
edition = "2021"
keywords = ["knowledge-management", "mobile", "decentralized", "webapp"]
license = "Apache-2.0"
name = "exomind-app"
repository = "https://github.com/appaquet/exomind"
version = "0.1.14"

[lib]
crate-type = ['cdylib']

[dependencies]
<<<<<<< Updated upstream
anyhow = "1.0.59"
=======
anyhow = "1.0.60"
>>>>>>> Stashed changes
exocore = { version = "0.1.22", default-features = false, features = ["apps-sdk"] }
exomind-protos = {version = "0.1.14", path = "../protos"}
futures = "0.3.21"
log = "0.4.17"
