FROM debian:buster-slim

ARG TARGETPLATFORM
ARG TARGETARCH

RUN echo "Building for platform $TARGETPLATFORM arch $TARGETARCH"
COPY "exomind-server-$TARGETARCH" /usr/local/bin/exomind-server

WORKDIR /volume
ENTRYPOINT ["/usr/local/bin/exomind-server"]
