[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["command-line-interface", "email", "text-editors"]
description = "Exomind, a personal knowledge management tool"
edition = "2021"
keywords = ["knowledge-management", "mobile", "decentralized", "webapp"]
license = "Apache-2.0"
name = "exomind-protos"
repository = "https://github.com/appaquet/exomind"
version = "0.1.27"

[dependencies]
exocore = { version = "0.1.27", path = "../../exocore", default-features = false, features = [
    "protos",
] }
prost = "0.13"
prost-types = "0.13"

[build-dependencies]
prost-build = "0.13"
