platform :ios, '17.0'
use_frameworks!

target 'ExamplesIos' do
  pod 'Exocore', :path => '../../Exocore.podspec'
  pod 'KeychainSwift'
end

# Prevent warning where pod minimum deployment target isn't matching the project's one
# See https://stackoverflow.com/questions/54704207/the-ios-simulator-deployment-targets-is-set-to-7-0-but-the-range-of-supported-d
post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      end
    end
end
