[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "Distributed applications framework"
edition = "2021"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exocore-apps-sdk"
repository = "https://github.com/appaquet/exocore"
version = "0.1.27"

[dependencies]
anyhow = "1.0.94"
exocore-apps-macros = {version = "0.1.27", path = "../macros"}
exocore-protos = {version = "0.1.27", path = "../../protos"}
exocore-store = {version = "0.1.27", path = "../../store", default-features = false}
futures = "0.3.31"
lazy_static = "1.5.0"
log = "0.4.22"
quote = "1.0.37"
thiserror = "2.0.6"
chrono = { version = "0.4.39", default-features = false, features = [] }

[dev-dependencies]
tokio = { version = "1.42.0", features = ["macros"], default-features = false }
