[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
name = "exomind-gmail"
version = "0.1.2"

[dependencies]
anyhow = "1.0"
base64 = "0.13"
chardetng = "0.1"
charset = "0.1"
exocore = {version = "0.1.5", default-features = false, features = ["client", "logger"]}
exomind-protos = {version = "0.1.2", path = "../../protos"}
google-gmail1 = "2.0"
hyper = "^0.14"
hyper-rustls = "^0.22"
log = "0.4"
mailparse = "0.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
structopt = "0.3"
tokio = {version = "1.6", features = ["macros", "rt-multi-thread", "time"]}
yup-oauth2 = "5.1"

[dev-dependencies]
exocore = {version = "0.1.5", default-features = false, features = ["client", "logger", "tests-utils"]}
