[package]
name = "exomind-gmail"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
google-gmail1 = { git = "https://github.com/appaquet/generated.git", branch = "gmail-labels-fix" }
google_api_auth = { git = "https://github.com/google-apis-rs/generator", features = ["with-yup-oauth2"] }
reqwest = { version = "0.9", default-features = false, features = ["rustls-tls"] } # to prevent linking w/ openssl
yup-oauth2 = "4.1.2"
exocore = { version = "0.1.1", default-features = false, features = ["client", "logger"] }
log = "0.4"
exomind-core = { version = "0.1.0", path = "../../core" }
mailparse = "0.13"
anyhow = "1.0"
charset = "0.1"
chardetng = "0.1"
structopt = "0.3"
serde = "1.0"
serde_yaml = "0.8"
serde_json = "1.0"
serde_derive = "1.0"
tokio = { version = "0.3", features = ["macros", "rt-multi-thread", "time"] }
tokio-compat-02 = "0.1"

[dev-dependencies]
exocore = { version = "0.1.1", default-features = false, features = ["client", "logger", "tests-utils"] }
