[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["command-line-interface", "email", "text-editors"]
description = "Gmail integration for Exomind, a personal knowledge management tool"
edition = "2021"
keywords = ["knowledge-management", "mobile", "decentralized", "gmail", "email"]
license = "Apache-2.0"
name = "exomind-gmail"
repository = "https://github.com/appaquet/exomind"
version = "0.1.13"

[dependencies]
anyhow = "1.0.57"
base64 = "0.13.0"
chardetng = "0.1.17"
charset = "0.1.3"
exocore = { version = "0.1.21", default-features = false, features = ["client", "logger"] }
exomind-protos = {version = "0.1.13", path = "../../protos"}
google-gmail1 = "3.1.0"
hyper = "0.14.18"
hyper-rustls = "0.23.0"
log = "0.4.17"
mailparse = "0.13.8"
serde = "1.0.137"
serde_derive = "1.0.136"
serde_json = "1.0.81"
serde_yaml = "0.8.24"
structopt = "0.3.26"

[dev-dependencies]
exocore = { version = "0.1.21", default-features = false, features = ["client", "logger", "tests-utils"] }
