[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["command-line-interface", "email", "text-editors"]
description = "Gmail integration for Exomind, a personal knowledge management tool"
edition = "2021"
keywords = ["knowledge-management", "mobile", "decentralized", "gmail", "email"]
license = "Apache-2.0"
name = "exomind-gmail"
repository = "https://github.com/appaquet/exomind"
version = "0.1.14"

[dependencies]
anyhow = "1.0.64"
base64 = "0.13.0"
chardetng = "0.1.17"
charset = "0.1.3"
duration-string = { version = "0.1.1", features = ["serde"] }
exocore = { version = "0.1.23", default-features = false, features = ["client", "logger"] }
exomind-protos = {version = "0.1.14", path = "../../protos"}
google-gmail1 = "4.0.1"
hyper = "0.14.20"
hyper-rustls = "0.23.0"
log = "0.4.17"
mailparse = "0.13.8"
serde = "1.0.145"
serde_derive = "1.0.142"
serde_json = "1.0.85"
serde_yaml = "0.9.11"
structopt = "0.3.26"

[dev-dependencies]
exocore = { version = "0.1.23", default-features = false, features = ["client", "logger", "tests-utils"] }
