[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["command-line-interface", "email", "text-editors"]
description = "Gmail integration for Exomind, a personal knowledge management tool"
edition = "2021"
keywords = ["knowledge-management", "mobile", "decentralized", "gmail", "email"]
license = "Apache-2.0"
name = "exomind-gmail"
repository = "https://github.com/appaquet/exomind"
version = "0.1.15"

[dependencies]
anyhow = "1.0.78"
base64 = "0.21.5"
chardetng = "0.1.17"
charset = "0.1.3"
duration-string = { version = "0.3.0", features = ["serde"] }
exocore = { version = "0.1.25", default-features = false, features = ["client", "logger"] }
exomind-protos = {version = "0.1.15", path = "../../protos"}
google-gmail1 = "5.0.3"
hyper = "0.14.28"
hyper-rustls = {version="0.24.2", features=["http2"]}
log = "0.4.20"
mailparse = "0.14.0"
serde = "1.0.193"
serde_derive = "1.0.193"
serde_json = "1.0.109"
serde_yaml = "0.9.29"
structopt = "0.3.26"

[dev-dependencies]
exocore = { version = "0.1.25", default-features = false, features = ["client", "logger", "tests-utils"] }
