FROM debian:buster-slim

ARG TARGETPLATFORM
ARG TARGETARCH

RUN echo "Building for platform $TARGETPLATFORM arch $TARGETARCH"
COPY "exomind-gmail-$TARGETARCH" /usr/local/bin/exomind-gmail

WORKDIR /volume
ENTRYPOINT ["/usr/local/bin/exomind-gmail"]
