name: Some Application
version: 0.0.1

public_key: peVpKYaERNKGhHRm7jEC1XXe4CUBWGv8g1QuDyDr76U1q

# Schema of the app.
# Use `protoc -I ../../protos -I . schema.proto -o schema.fd` to generate from proto
schemas:
  - file: schema.fd
