# Until Dependabot supports it...
# From https://github.com/dependabot/dependabot-core/issues/2268#issuecomment-831376155

name: automerge
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: "Merge PR"
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.workflow_run.pull_requests[0].number,
            });
            if (pr.data.title.startsWith('chore(deps-dev):') && pr.data.user.login === 'dependabot[bot]') {
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.workflow_run.pull_requests[0].number,
              });
              console.log('Merged 🎉');
            } else {
              console.log('Not Merged 🚫');
            }
