# Seperate push-tester for iOS since MacOS machines are 10x the price. To be moved back when open sourced.

name: iOS push tester

on:
  push:
    paths:
    - 'ios/**'

jobs:
  ios_build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2.3.2

      - name: Install dependencies
        run: |
          brew install swift-protobuf

      - name: Force Xcode 11.5
        run: sudo xcode-select -switch /Applications/Xcode_11.5.app

      - name: Build 
        run: |
          cd $GITHUB_WORKSPACE/ios
          pod install
          xcodebuild -workspace Exomind.xcworkspace -scheme Exomind -destination "generic/platform=iOS" CODE_SIGNING_ALLOWED=NO 

